version: '3'
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    container_name: app
    build:
      dockerfile: ./TechnicalTest/Dockerfile
      context: .
    restart: always
    # command: bash -c "dotnet ef database update && dotnet watch run"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=dev123
    ports:
      - 5000:80
      - 5001:443
    networks:
      - restapi_network
    depends_on:
      - postgres
    links:
      - postgres
  ### ===================
  ### DB SERVICE
  ### ===================
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    networks:
      - restapi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
### ========================
### VOLUMES PERSISTENT DATA
### ========================
volumes:
    progresDB:
### ===================================
### NETWORKS GROUP FOR ONE SAME SERVICE
### ===================================
networks:
    restapi_network: